Patch 4
logicplace/c88-pokemini pull request #2
Opened 2021-09-04 07:59 UTC by Jhynjhiruu

Needs testing on Linux
Also your rm detection is broken on my machine, doesn't really matter because cmd but still

2021-09-04 08:13 UTC, logicplace requested changes

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
I don't really like it but it's whatever ultimately, at the very least these have nothing to do with wine, so please rename the variable.

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> +.PHONY: all, run, assembly
I'm pretty sure MK88 doesn't support .PHONY but it also doesn't care about it at least. Did you test or is it just here for other make systems?

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> +.DEFAULT: all
I think you misunderstood what .DEFAULT does. Basically if you say `make jejfkfkdjdj` it will run .DEFAULT, which is obviously inappropriate.

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> +	$(POKEMINID) $(TARGET).min
Why add duplication?

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> -$(TARGET).hex: $(TARGET).out
You're welcome to add the .map part here. But please keep the implicit rules instead.

2021-09-04 08:13 UTC, logicplace commented on pm.mk
> +.SUFFIXES: .min .hex .map .abs .c .c.asm .asm .obj .out
Two periods in a .SUFFIXES entry doesn't actually seem to function, I tried everything I could think of.

2021-09-04 08:19 UTC, Jhynjhiruu commented on pm.mk
> +.SUFFIXES: .min .hex .map .abs .c .c.asm .asm .obj .out
Oh, yeah, that needs removing, it's a leftover (make assembly generates .s files now to avoid overwriting .asm files)

2021-09-04 08:19 UTC, Jhynjhiruu commented on pm.mk
> +	$(POKEMINID) $(TARGET).min
Can't remember for the life of me

2021-09-04 08:19 UTC, Jhynjhiruu commented on pm.mk
> +.DEFAULT: all
But, now just running `mk88` will build the .min which is very nice

2021-09-04 08:20 UTC, Jhynjhiruu commented on pm.mk
> +.PHONY: all, run, assembly
Just there because I copied this from pm.mk

2021-09-04 08:20 UTC, Jhynjhiruu commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
Uhhh what

2021-09-04 08:21 UTC, logicplace commented on pm.mk
> +.DEFAULT: all
It already did??

2021-09-04 08:22 UTC, Jhynjhiruu commented on pm.mk
> -$(TARGET).hex: $(TARGET).out
What

2021-09-04 08:25 UTC, logicplace commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
Running from PATH is typical and I think what we should do, primarily because who knows what version of PokeMiniD is included in bin-windows. But if this seems too difficult or something and we absolutely need to do it this way, instead of changing path or just putting srec_cat somewhere else, it's fine. But in that case, the conditioned macro needs to change from WINE to e.g. LINUX. Or more likely, invert the conditional and do ifdef WINDOWS

2021-09-04 08:36 UTC, logicplace commented on pm.mk
> -$(TARGET).hex: $(TARGET).out
Basically, leave the .s and the assembly command then change all the rest of rule code back to the way it was.

2021-09-04 08:41 UTC, Jhynjhiruu commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
Ohhh right, yeah. But - it seems to make more sense to assume that if people are running mk88, they're using Windows? Since it's a Windows program? If they're already using Wine to run mk88, they have to have a more complex command line anyway - so having a flag for Linux rather than Windows makes more sense to me.

2021-09-04 08:42 UTC, Jhynjhiruu commented on pm.mk
> +.DEFAULT: all
...oh huh. Didn't seem to before, maybe I messed something else up.

2021-09-04 08:48 UTC, logicplace commented on pm.mk
> +.DEFAULT: all
The .PHONY may have broken it? Only thing I can't think of.

2021-09-04 08:52 UTC, logicplace commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
I don't think that's a fair assumption since the entire build chain is Windows. But that does bring up the question that, if you run this thru `wine mk88`, do we even need to account for Linux? Won't it just use Wine's CMD? 💦💦

2021-09-04 17:35 UTC, logicplace commented on pm.mk
> +.DEFAULT: all
Double checked, works fine even with .PHONY so we're good here.

2021-09-04 18:06 UTC, Jhynjhiruu commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
I did ask that and didn't really receive a good response. We'd need someone who uses Linux to test it out for us.

2021-09-06 02:39 UTC, logicplace commented on pm.mk
> +POKEMINID := $(PRODDIR)/../bin-windows/PokeMiniD
So yeah running thru wine makes this use CMD, so `wine` and stuff isn't around. We can address this in a separate PR

2021-09-06 02:40 UTC, logicplace approved these changes

2021-09-06 02:40 UTC, merged